name: Changelog Update

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

permissions: write-all

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Update Changelog
        run: |
          echo "## PR #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}" >> CHANGELOG.md
          echo "- ${{ github.event.pull_request.body }}" >> CHANGELOG.md
          echo "" >> CHANGELOG.md

      - name: Commit and push changelog update
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md for PR #${{ github.event.pull_request.number }}"
          git push origin HEAD:refs/heads/${{ github.head_ref }}
